# Generated by Django 4.2.26 on 2026-05-15 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0047_remove_preprintauthor_affiliation_and_more'),
        ('geometadata', '0002_add_bbox_index'),
    ]

    operations = [
        migrations.CreateModel(
            name='RepositoryPluginSetting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('setting_name', models.CharField(max_length=200, verbose_name='Setting name')),
                ('value', models.TextField(blank=True, verbose_name='Value')),
            ],
            options={
                'verbose_name': 'Repository Plugin Setting',
                'verbose_name_plural': 'Repository Plugin Settings',
            },
        ),
        migrations.RenameIndex(
            model_name='articlegeometadata',
            new_name='articlegeometadata_bbox_idx',
            old_name='articlegeom_bbox_idx',
        ),
        migrations.RenameIndex(
            model_name='preprintgeometadata',
            new_name='preprintgeometadata_bbox_idx',
            old_name='preprintgeo_bbox_idx',
        ),
        migrations.AddField(
            model_name='repositorypluginsetting',
            name='repository',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometadata_settings', to='repository.repository', verbose_name='Repository'),
        ),
        migrations.AddIndex(
            model_name='repositorypluginsetting',
            index=models.Index(fields=['repository', 'setting_name'], name='geometadata_reposit_3ec2bf_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='repositorypluginsetting',
            unique_together={('repository', 'setting_name')},
        ),
    ]
