# Generated by Django 4.2.26 on 2026-05-17 17:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repository', '0047_remove_preprintauthor_affiliation_and_more'),
        ('geometadata', '0003_add_repository_plugin_setting'),
    ]

    operations = [
        migrations.AddField(
            model_name='preprintgeometadata',
            name='preprint_version',
            field=models.ForeignKey(blank=True, help_text='The PreprintVersion this geometadata describes. Leave blank for the legacy / canonical state shared across versions.', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='geometadata', to='repository.preprintversion', verbose_name='Preprint version'),
        ),
        migrations.AlterField(
            model_name='preprintgeometadata',
            name='preprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='geometadata_set', to='repository.preprint', verbose_name='Preprint'),
        ),
        migrations.AlterUniqueTogether(
            name='preprintgeometadata',
            unique_together={('preprint', 'preprint_version')},
        ),
    ]
